version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: edwardsjewelersdb
      POSTGRES_USER: edwaeardsjewelersadmin
      POSTGRES_PASSWORD: edwardsjewelerspassword

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: '1'
      DATABASE_HOST: db
      DATABASE_NAME: edwardsjewelersdb
      DATABASE_USER: edwaeardsjewelersadmin
      DATABASE_PASSWORD: edwardsjewelerspassword

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "5050:80"
    depends_on:
      - db

networks:
  default:
    driver: bridge

volumes:
  postgres_data:

